PUT http://localhost:8080/api/meetings/1/intervals/user1
Content-Type: application/json

{
  "intervals": [
    {
      "from": 1652214240000,
      "to": 1652300640000
    },
    {
      "from": 1652300650000,
      "to": 1652300660000
    }
  ]
}
