# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build PR with Maven

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.java'
      - '**.css'
      - '**.html'
      - '**.yml'
      - '**.yaml'
      - '**.json'
      - '**/pom.xml'
      - '**.properties'
      - '**Dockerfile'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./target/site/jacoco/jacoco.xml

  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: react-client/package-lock.json

      - name: Build client and copy to backend resources
        run: |
          cd react-client
          npm install
          npm run build
