name: Build

on:
  push:
    tags:
      - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: react-client/package-lock.json

      - name: Build client and copy to backend resources
        run: |
          cd react-client
          npm install
          npm run build
          rm -rf ../src/main/resources/public/static/
          \cp -r ./build/* ../src/main/resources/public/

      - name: Build docker container and push
        run: |
          ./mvnw -B package docker:build docker:push

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./target/site/jacoco/jacoco.xml
