name: Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Print ref"
        run: echo "Triggered by ref ${GITHUB_REF_NAME}"

      - name: "Set version variable"
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.3
        with:
          app_name: meeting-assistant
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                     {
                       "name": "solomkinmv-meeting-assistant",
                       "image": {
                         "registry_type": "DOCKER_HUB",
                         "registry": "solomkinmv",
                         "repository": "meeting-assistant",
                         "tag": "${{ env.VERSION }}"
                       }
                     }
                   ]'
