name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
        with:
          tagRegex: "v(.*)"

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.3
        with:
          app_name: meeting-assistant
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                     {
                       "name": "solomkinmv-meeting-assistant",
                       "image": {
                         "registry_type": "DOCKER_HUB",
                         "registry": "solomkinmv",
                         "repository": "meeting-assistant",
                         "tag": "${{ env.GIT_TAG_NAME }}"
                       }
                     }
                   ]'
