name: Release version
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Configure Git user
      run: |
        git config user.email "ci-bot@solomk.in"
        git config user.name "ci-bot"

    - name: Make release
      run: ./mvnw -B release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
