name: Release version
on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.java'
      - '**.css'
      - '**.html'
      - '**.yml'
      - '**.yaml'
      - '**/pom.xml'
      - '**.properties'
      - '**Dockerfile'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI]') && !contains(github.event.head_commit.message, '[skip release]')"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Increment service version for release
        run: |
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git commit -am "[CI] prepare release v$VERSION"    
          git tag "v$VERSION" 
          git push --atomic origin main "v$VERSION"    

      - name: Increment service version for next development iteration
        run: |
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          git add ./\pom.xml
          git commit -m "[CI] prepare for next development iteration"    
          git push origin main

