name: Release version
on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.java'
      - '**.css'
      - '**.html'
      - '**.yml'
      - '**.yaml'
      - '**/pom.xml'
      - '**.properties'
      - '**Dockerfile'

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI]') && !contains(github.event.head_commit.message, '[skip release]')"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build client and push to backend resources
        run: npm run deploy

      - name: Make release
        run: ./mvnw -B release:prepare release:perform

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./target/site/jacoco/jacoco.xml
