name: Release version
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Release
      uses: qcastel/github-actions-maven-release@v1.12.34
      with:
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@solomk.in"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests"
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
